builds:
  -
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
dist: releases
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: pete911
    name: template-wh
