---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        env:
        - name: TWH_CONFIGMAP_NAME
          value: {{ .Release.Name }}
        - name: TWH_CONFIGMAP_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: TWH_TLS_CRT
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: tls.crt
        - name: TWH_TLS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: tls.key
        resources:
          limits:
            cpu: 150m
            memory: 256Mi
          requests:
            cpu: 150m
            memory: 256Mi
