name: release

on:
  push:
    branches:
      - main
    paths:
      - "charts/template-wh/Chart.yaml"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get helm chart version
        run: echo "CHART_VERSION=$(grep '^version:' charts/template-wh/Chart.yaml | cut -d ":" -f2 | tr -d ' ')" >> $GITHUB_ENV

      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.CHART_VERSION }}",
              sha: context.sha
            })
